-- 온라인 판매 데이터 조회
SELECT
  DATE_FORMAT(O.SALES_DATE, "%Y-%m-%d") SALES_DATE,
  O.PRODUCT_ID,
  O.USER_ID,
  O.SALES_AMOUNT
FROM
  ONLINE_SALE O
WHERE
  O.SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'

UNION

-- 오프라인 판매 데이터 조회
SELECT
  DATE_FORMAT(F.SALES_DATE, "%Y-%M-%D") SALES_DATE, # DATE_FORMAT
  F.PRODUCT_ID,
  NULL AS USER_ID, # null as user_id
  F.SALES_AMOUNT
FROM
  OFFLINE_SALE F
WHERE
  F.SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31' # between a and b

ORDER BY
  SALES_DATE,
  PRODUCT_ID,
  USER_ID;